#generated by qwen3-coder:30b valid
def solve_safe_password(rotations):
    current_position = 50
    count_zeros = 0

    for rotation in rotations:
        direction = rotation[0]
        distance = int(rotation[1:])

        if direction == 'L':
            current_position -= distance
        else:
            current_position += distance

        current_position %= 100

        if current_position == 0:
            count_zeros += 1

    return count_zeros

# Read rotations from file
with open('day1/input.txt', 'r') as f:
    rotations = [line.strip() for line in f]

password = solve_safe_password(rotations)
print(password)