#generated by qwen3-coder:30b almost valid
def is_invalid_id(id_str):
    """Check if an ID is invalid (made of repeated digits)"""
    if len(id_str) % 2 != 0:
        return False
    
    half_length = len(id_str) // 2
    first_half = id_str[:half_length]
    second_half = id_str[half_length:]
    
    return first_half == second_half

def solve_product_ids(input_line):
    # Parse the input line into ranges
    ranges = input_line.strip().split(',')
    
    invalid_count = 0
    
    for range_str in ranges:
        if '-' in range_str:
            start, end = map(int, range_str.split('-'))
            # Check each ID in the range
            for id_num in range(start, end + 1):
                id_str = str(id_num)
                if is_invalid_id(id_str):
                    invalid_count += id_num #CORRECTED: invalid_count += 1 ----> invalid_count += id_num
    
    return invalid_count

# Read input from file
with open('day2/input.txt', 'r') as f:
    input_line = f.read().strip()

result = solve_product_ids(input_line)
print(result)
